### ISSUE TITLE
Mod chatshot provides a broken implementation of ModMenuApi

### ISSUE THREAD

**Issue by 0xallie** [DeDiamondPro/ChatShot#1]
```
[12:13:24] [Render thread/ERROR]: Mod chatshot provides a broken implementation of ModMenuApi
java.lang.NoClassDefFoundError: dev/isxander/yacl3/api/controller/ControllerBuilder
	at dev.dediamondpro.chatshot.config.ModMenuIntegration.getModConfigScreenFactory(ModMenuIntegration.java:12) ~[transformed-mod-chatshot.i0:0/:?]
	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$1(ModMenu.java:75) ~[transformed-mod-modmenu.i0:0/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:70) ~[transformed-mod-modmenu.i0:0/:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$1(Hooks.java:56) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:56) ~[quilt-loader-0.20.2.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.20.2.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: dev.isxander.yacl3.api.controller.ControllerBuilder
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:178) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150) ~[quilt-loader-0.20.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.20.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 22 more
```

# Environment
* macOS 13.5.2
* OpenJDK Runtime Environment Temurin-17.0.8.1+1
* Minecraft 1.20.1
* Quilt Loader 0.20.2
* Quilted Fabric API 7.2.1+0.88.0-1.20.1
* Cloth Config 11.1.106
* Mod Menu 7.2.2
* ChatShot 1.0.0 (Modrinth)

**Comment by DeDiamondPro** [comment]
This is normal behavior if yacl is not installed, you can install it from https://modrinth.com/mod/yacl/versions

**Comment by 0xallie** [comment]
Ah yes, I installed it for another mod which outright requires YACL in meantime and the error has gone away.
